name: Main workflow

on: push
jobs:
    make-artifact:
        runs-on: ubuntu-latest
        steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subsito/flutter-actions@v2
          with:
            flutter-version: 3.19.5
        - run: flutter pub get
        - run: flutter build apk
        - name: Upload artifact
          uses: actions/upload-artifact@v1
          with:
            name: release-apk
            path: build/app/outputs/apk/release/app-release.apk

